## Логирование (достаточно для учебной среды)
log.console.level = info

## Загрузка топологии и пользователей при старте
management.load_definitions = /etc/rabbitmq/definitions.json

## AMQP (без TLS)
listeners.tcp.default = 5672

## AMQP + TLS (клиентские сертификаты не обязательны)
listeners.ssl.default = 5671
ssl_options.cacertfile = /cert/ca.pem
ssl_options.certfile = /cert/server_cert.pem
ssl_options.keyfile = /cert/server_key.pem
ssl_options.verify = verify_none
ssl_options.fail_if_no_peer_cert = false

## Management UI / API
management.tcp.port = 15672

## MQTT
mqtt.listeners.tcp.default = 1883
mqtt.allow_anonymous = false
mqtt.vhost = bakery

## STOMP
stomp.listeners.tcp.1 = 61613

## RabbitMQ Stream (порт нативного stream-протокола)
stream.listeners.tcp.default = 5552
